FROM prom/prometheus:v2.0.0

# file di configurazione (prometheus.yml e alert.rules)
COPY config.yml /etc/prometheus/config.yml
COPY alert.rules /etc/prometheus/alert.rules

# Comando per avviare Prometheus con i file di configurazione
CMD ["--config.file=/etc/prometheus/config.yml", \
     "--storage.tsdb.path=/prometheus", \
     "--web.console.libraries=/usr/share/prometheus/console_libraries", \
     "--web.console.templates=/usr/share/prometheus/consoles", \
     "--web.enable-lifecycle"]