apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: init-postgres 
        image: busybox 
        command: ['sh', '-c', 'until nc -z -v -w30 postgres 5432; do echo "Waiting for PostgreSQL..."; sleep 5; done'] 
      - name: init-kafka 
        image: busybox 
        command: ['sh', '-c', 'until nc -z -v -w30 kafka-broker 9092; do echo "Waiting for Kafka..."; sleep 5; done']
      containers:
      - name: server-container
        image: francescoromeo/dsbd_hw_server:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          value: "toor"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker:9092"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: grpc-server-port
      protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30001
    - name: prometheus-server-port
      protocol: TCP
      port: 50055
      targetPort: 50055