apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server-container
        image: dsbd_hw1-server:latest
        env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          value: "toor"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker:9092"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051