global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'fraromeo14@gmail.com'
        from: '${EMAIL_SENDER_USER}'
        smarthost: 'smtp.gmail.com:587'
        auth_username: '${EMAIL_SENDER_USER}'
        auth_password: '${EMAIL_SENDER_PASSWORD}'
        auth_identity: '${EMAIL_SENDER_USER}'
